package January2024;


// Generated by CodiumAI

import January2024.Jan4;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class Jan4Test {


    // Valid palindrome input returns true
    @Test
    public void test_valid_palindrome_input_returns_true() {
        // Given
        String input = "aba";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertTrue(result);
    }

    // Palindrome with odd length returns true
    @Test
    public void test_palindrome_with_odd_length_returns_true() {
        // Given
        String input = "abcba";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertTrue(result);
    }

    // Palindrome with even length returns true
    @Test
    public void test_palindrome_with_even_length_returns_true() {
        // Given
        String input = "abba";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertTrue(result);
    }

    // Empty string input returns true
    @Test
    public void test_empty_string_input_returns_true() {
        // Given
        String input = "";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertTrue(result);
    }

    // Palindrome with two characters returns true
    @Test
    public void test_palindrome_with_two_characters_returns_true() {
        // Given
        String input = "aa";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertTrue(result);
    }

    // Non-palindrome with two characters returns false
    /*@Test
    public void test_non_palindrome_with_two_characters_returns_false() {
        // Given
        String input = "ab";

        // When
        boolean result = Jan4.validPalindrome(input);

        // Then
        assertFalse(result);
    }
*/
}
